### ISSUE TITLE
Missing dependency "isomorphic-fetch"

### ISSUE THREAD

**Issue by TravelingTechGuy** [escaladesports/react-netlify-form#13]
I tried installing the module with both `npm install` and `yarn add`. Both times I get the same error when trying to build the project:

```
.\node_modules\react-netlify-form\dist\process.js
Cannot find module: 'isomorphic-fetch'. Make sure this package is installed.

You can install this package by running: yarn add isomorphic-fetch.
```

Adding the module manually solves the problem

## Expected behavior

I expect it to either be installed automatically as a dependency, or for the documentation to show that you need to 

`yarn add react-netlify-form isomorphic-fetch`

**Comment by kennedyrose** [comment]
Fixed with https://github.com/escaladesports/react-netlify-form/commit/8a4f77f13817c07f8c90d0f478366e49b2e33db2
