### ISSUE TITLE
Object.entries Polyfill

### ISSUE THREAD

**Issue by AustinLeeGordon** [escaladesports/react-netlify-form#3]
Having issues with the Object.entries method on IE form submit. I included `Object.entries` in the polyfill but it doesn't load in.

`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Object.entries"></script>`

![console error](https://user-images.githubusercontent.com/19353967/43841190-2f29fa08-9ae8-11e8-928a-0e2cdadb7eae.PNG)

**Comment by AustinLeeGordon** [comment]
I also tried adding `|always` to `Object.entries` in the query. It gives the same error.

**Comment by kennedyrose** [comment]
I'm looking into baking all polyfills into this component at the moment.

**Comment by AustinLeeGordon** [comment]
@kennedyrose Okay, thank you!

**Comment by AustinLeeGordon** [comment]
@kennedyrose Any update on this? I tried forking it and using that on our site but your build scripts don't work for me. Also realized that it had to do with FormData instead of Object.assign haha

**Comment by kennedyrose** [comment]
Sorry for the delay. This would up being a more complicated issue getting the polyfill into the build. Webpack doesn't like the polyfill for some reason and refuses to build with it.

It should work if you include this [formdata polyfill](https://www.npmjs.com/package/formdata-polyfill) somewhere in your client side in the meantime.

**Comment by AustinLeeGordon** [comment]
No worries! I really appreciate you taking the time to fix it! I'll have to check out the new boilerplate when you're finished with it. I've been planning to get more into testing and TDD. Thanks again!
